#!/bin/bash

DB_USER=$SNAPPY_USER
DB_PASS=$SNAPPY_PW
DB=$SNAPPY_DB
IP=$SNAPPY_HOST
PORT=$SNAPPY_PORT

#echo $DB_USER
#echo $DB_PASS
#echo $DB
#echo $IP
#echo $PORT

mysql -u "$DB_USER" -h "$IP" -P "$PORT" --database="$DB" --password="$DB_PASS" -e "SELECT * FROM jobs"
