#!/bin/bash

USAGE="Usage:  ./arg2_builder <source_id> <target_id> <image_id>"

if [[ "$#" -ne 3 ]]
then
  echo -e $USAGE
  exit 1
fi

SOURCE_PROFILE=$1
TARGET_PROFILE=$2
IMAGE_ID=$3

# get the source and target JSON files from the local sqlite3 DB
TEMP_SOURCE_JSON=$(builder_utils/jsonselectsource $SOURCE_PROFILE)
TARGET_JSON=$(builder_utils/jsonselecttarget $TARGET_PROFILE)

# We need to add in another key/value pair to the source so we can fill in the RBD image later
SOURCE_JSON=$(echo $TEMP_SOURCE_JSON | jq '.sp_param=(.sp_param + {"image":"RBD_IMAGE_ID"})')

#combine those JSON strings together into one
COMBINED=$(echo $SOURCE_JSON $TARGET_JSON | jq -s add)

# insert the volume image ID
ARG2=$(echo \'$COMBINED\' | sed -e "s~RBD_IMAGE_ID~$IMAGE_ID~g")

echo $ARG2

