#!/bin/bash


USAGE="Usage:  ./add_backup_single_scheduled <volume_uuid> <backup_interval_in_secs> <#_of_backups> <source_id> <target_id> <original_source_type> <original_source_id>"

if [[ "$#" -ne 7 ]]
then
  echo -e $USAGE
  exit 1
fi

RBD_IMAGE_ID=$1
BACKUP_INTERVAL=$2
NUM_BACKUPS=$3
SOURCE_ID=$4
TARGET_ID=$5
ORIG_SRC_TYPE=$6
ORIG_SRC_ID=$7

# since we're not doing incremental backups here, make the interval for it
# bigger than the full backup interval so that it never gets executed
BIGGER_INTERVAL=`expr $BACKUP_INTERVAL + 1`

# contruct argument 1 for the database entry
ARG1=$(builder_utils/arg1_builder $BACKUP_INTERVAL $BIGGER_INTERVAL $NUM_BACKUPS)

# construct argument 2 for the database entry
ARG2=$(builder_utils/arg2_builder $SOURCE_ID $TARGET_ID $RBD_IMAGE_ID)

DB_USER=$SNAPPY_USER
DB_PASS=$SNAPPY_PW
DB=$SNAPPY_DB
IP=$SNAPPY_HOST
PORT=$SNAPPY_PORT

echo "logging into db "$DB" as "$DB_USER" at "$IP" port "$PORT

LOG=$(builder_utils/log_builder $ORIG_SRC_TYPE $ORIG_SRC_ID)

# Since the FEID field is only 36 characters, truncate it if necessary (use the last 36)
FEID36=$(echo -n $RBD_IMAGE_ID | tail -c 36)

CMD="start transaction; insert into jobs (feid,policy,arg0,arg1,arg2,log) values ('$FEID36',7,'bk_single_sched',$ARG1,$ARG2,$LOG);SELECT last_insert_id(); commit"

echo $CMD

mysql -u "$DB_USER" -h "$IP" -P"$PORT" --database="$DB" --password="$DB_PASS"  -e "$CMD"
